services:
  - type: web
    name: mobilya-tasarim-api
    runtime: go
    region: frankfurt
    plan: free
    buildCommand: cd server && go build -o ../app .
    startCommand: ./app
    envVars:
      - key: PORT
        value: "10000"
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
